spring:
  datasource:
    url: jdbc:h2:mem:motionlabs
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console
  sql:
    init:
      mode: always
      encoding: UTF-8
      data-locations: classpath:db/data.sql

  jpa:
    hibernate:
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
    open-in-view: false
    defer-datasource-initialization: true

logging:
  level:
    com.motionlabs: debug
    org.hibernate.SQL: debug